name: frame_locator_pin
description: "Uses the compass heading of Frame to display pins representing locations of interest"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.33.6
  logging: ^1.3.0
  simple_frame_app:
    path: ../simple_frame_app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - packages/simple_frame_app/lua/battery.min.lua
  - packages/simple_frame_app/lua/data.min.lua
  - packages/simple_frame_app/lua/code.min.lua
  - packages/simple_frame_app/lua/imu.min.lua
  - packages/simple_frame_app/lua/sprite.min.lua
  - packages/simple_frame_app/lua/plain_text.min.lua
  - assets/sprite_position.min.lua
  - assets/multi_poi.lua
  - assets/frame_app.lua
  - assets/sprites/20_fav64.png
  - assets/sprites/21_bank64.png
  - assets/sprites/22_left64.png
  - assets/sprites/23_right64.png
