name: frame_locator_pin
description: "Uses the compass heading of Frame to display pins representing locations of interest"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.33.6
  logging: ^1.3.0
  shared_preferences: ^2.3.2
  simple_frame_app: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - packages/simple_frame_app/lua/battery.min.lua
  - packages/simple_frame_app/lua/data.min.lua
  - packages/simple_frame_app/lua/code.min.lua
  - packages/simple_frame_app/lua/imu.min.lua
  - packages/simple_frame_app/lua/plain_text.min.lua
  - assets/frame_app.lua
